import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white font-medium`}>
        <Header />
        {children}
        <footer className="py-[80px] bg-black">
          <div className="container">
            <div className="flex flex-col items-center gap-[52px]">
              <img src="./images/logo.png" alt="logo" className="max-w-[191px]" />
              <nav className="flex flex-row gap-[27px] text-white">
                <Link href='/domestic'>Domestic</Link>
                <Link href='/commercial'>Commercial</Link>
                <Link href='/about'>About Us</Link>
                <Link href='/contact'>Contact</Link>
              </nav>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
